package org.cland.plantuml;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates PlantUML .puml diagram text from parsed type models.
 */
public class PumlGenerator {

    private final boolean hideJavaLang;
    private final boolean onlyPublic;

    public PumlGenerator(boolean hideJavaLang, boolean onlyPublic) {
        this.hideJavaLang = hideJavaLang;
        this.onlyPublic = onlyPublic;
    }

    /**
     * Generates a PlantUML class diagram.
     */
    public String generateClassDiagram(JavaSourceScanner.ScanResult result) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("' Generated by cland-plantuml\n");
        sb.append("' Classes: ").append(result.types.size()).append("\n");
        sb.append("' Date: ").append(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)).append("\n");
        sb.append("\n");
        sb.append("hide empty members\n");

        if (hideJavaLang) {
            sb.append("hide java.lang\n");
        }

        for (TypeModel type : result.types.values()) {
            String kind = type.kind.equals("record") ? "class" : type.kind;
            sb.append(kind).append(" ").append(type.qualifiedName());
            if (type.kind.equals("record")) {
                sb.append(" <<record>>");
            }
            sb.append(" {\n");

            // Fields
            List<TypeModel.Member> fields = onlyPublic
                ? type.fields.stream().filter(m -> m.visibility.equals("public")).collect(Collectors.toList())
                : type.fields;
            for (TypeModel.Member field : fields) {
                sb.append("  ").append(visSymbol(field.visibility))
                  .append(" ").append(field.type).append(" ").append(field.name).append("\n");
            }

            // Separator
            if (!fields.isEmpty() && !type.methods.isEmpty()) {
                sb.append("  ..\n");
            }

            // Methods
            List<TypeModel.Member> methods = onlyPublic
                ? type.methods.stream().filter(m -> m.visibility.equals("public")).collect(Collectors.toList())
                : type.methods;
            for (TypeModel.Member method : methods) {
                sb.append("  ").append(visSymbol(method.visibility))
                  .append(" ").append(method.type).append(" ").append(method.name).append("()\n");
            }

            sb.append("}\n\n");
        }

        sb.append("@enduml\n");
        return sb.toString();
    }

    /**
     * Generates a PlantUML package dependency diagram.
     */
    public String generatePackageDiagram(JavaSourceScanner.ScanResult result) {
        StringBuilder sb = new StringBuilder();
        sb.append("@startuml\n");
        sb.append("' Generated by cland-plantuml - Package Diagram\n\n");

        // Collect packages from filtered types
        Set<String> packages = result.types.values().stream()
            .map(t -> t.packageName)
            .filter(Objects::nonNull)
            .collect(Collectors.toCollection(TreeSet::new));

        for (String pkg : packages) {
            sb.append("package ").append(pkg).append(" {\n}\n\n");
        }

        // Package dependencies
        for (Map.Entry<String, Set<String>> entry : result.packageDeps.entrySet()) {
            String from = entry.getKey();
            for (String to : entry.getValue()) {
                // Only show dependency if the target package is in our filtered set
                if (packages.stream().anyMatch(to::startsWith)) {
                    sb.append(from).append(" --> ").append(to).append("\n");
                }
            }
        }

        sb.append("@enduml\n");
        return sb.toString();
    }

    private static String visSymbol(String vis) {
        switch (vis) {
            case "public":    return "+";
            case "private":   return "-";
            case "protected": return "#";
            default:          return "~";
        }
    }
}
