/*
 * cland-plantuml — Java source to PlantUML diagram generator
 */
package org.cland.plantuml;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/** Generates PlantUML .puml diagram text from parsed type models. */
public class PumlGenerator {

		private final boolean hideJavaLang;
		private final boolean onlyPublic;
		private final boolean showRelationships;

		public PumlGenerator(boolean hideJavaLang, boolean onlyPublic) {
				this(hideJavaLang, onlyPublic, true);
		}

		public PumlGenerator(boolean hideJavaLang, boolean onlyPublic, boolean showRelationships) {
				this.hideJavaLang = hideJavaLang;
				this.onlyPublic = onlyPublic;
				this.showRelationships = showRelationships;
		}

		/** Generates a PlantUML class diagram. */
		public String generateClassDiagram(JavaSourceScanner.ScanResult result) {
				StringBuilder sb = new StringBuilder();
				sb.append("@startuml\n");
				sb.append("' Generated by cland-plantuml\n");
				sb.append("' Classes: ").append(result.types.size()).append("\n");
				sb.append("' Date: ")
								.append(LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME))
								.append("\n");
				sb.append("\n");
				sb.append("hide empty members\n");

				if (hideJavaLang) {
						sb.append("hide java.lang\n");
				}

				// ── Type boxes ──
				for (TypeModel type : result.types.values()) {
						emitTypeBox(sb, type);
				}

				// ── Relationship arrows ──
				if (showRelationships) {
						Set<String> emitted = new HashSet<>();
						for (TypeModel type : result.types.values()) {
								for (String arrow : type.relationshipArrows()) {
										// Only emit arrows where the target type is known in the diagram
										String target = parseArrowTarget(arrow);
										if (target != null && !result.types.containsKey(target)) continue;
										if (emitted.add(arrow)) {
												sb.append(arrow).append("\n");
										}
								}
						}
				}

				sb.append("@enduml\n");
				return sb.toString();
		}

		private void emitTypeBox(StringBuilder sb, TypeModel type) {
				// Kind prefix
				String kind = type.plantUmlKind();
				sb.append(kind).append(" ").append(type.qualifiedName());

				// Type parameters
				if (!type.typeParameters.isEmpty()) {
						sb.append("<").append(String.join(", ", type.typeParameters)).append(">");
				}

				// Stereotypes
				List<String> stereotypes = new ArrayList<>();
				if (type.isRecord()) {
						stereotypes.add("record");
				}
				if (type.kind.equals("annotation")) {
						stereotypes.add("annotation");
				}
				for (String ann : type.annotations) {
						stereotypes.add(ann);
				}
				if (!stereotypes.isEmpty()) {
						sb.append(" <<").append(String.join(", ", stereotypes)).append(">>");
				}

				// Extends / implements in class header
				String extendsClause = type.extendsClause();
				String implementsClause = type.implementsClause();
				if (!extendsClause.isEmpty() || !implementsClause.isEmpty()) {
						sb.append(extendsClause).append(implementsClause);
				}

				sb.append(" {\n");

				// Enum constants
				if (!type.enumConstants.isEmpty()) {
						for (String ec : type.enumConstants) {
								sb.append("  ").append(ec).append("\n");
						}
						if (!type.fields.isEmpty() || !type.methods.isEmpty()) {
								sb.append("  ..\n");
						}
				}

				// Fields
				List<TypeModel.Member> fields =
								onlyPublic
												? type.fields.stream()
																.filter(m -> m.visibility.equals("public"))
																.collect(Collectors.toList())
												: type.fields;
				for (TypeModel.Member field : fields) {
						sb.append("  ")
										.append(field.plantUmlSymbol())
										.append(" ")
										.append(field.type)
										.append(" ")
										.append(field.name)
										.append("\n");
				}

				// Separator
				if (!fields.isEmpty() && !type.methods.isEmpty()) {
						sb.append("  ..\n");
				}

				// Methods
				List<TypeModel.Member> methods =
								onlyPublic
												? type.methods.stream()
																.filter(m -> m.visibility.equals("public"))
																.collect(Collectors.toList())
												: type.methods;
				for (TypeModel.Member method : methods) {
						sb.append("  ")
										.append(method.plantUmlSymbol())
										.append(" ")
										.append(method.type)
										.append(" ")
										.append(method.name)
										.append("()\n");
				}

				sb.append("}\n\n");

				// Inner types
				for (TypeModel inner : type.innerTypes) {
						emitTypeBox(sb, inner);
				}
		}

		/**
		 * Parse the target type from a relationship arrow string. Arrows have the form: {@code Source
		 * --> Target} or {@code Target <|-- Source}.
		 *
		 * @return the fully qualified target type name, or null if unparseable
		 */
		private static String parseArrowTarget(String arrow) {
				// Pattern: "A --> B" → target is B
				int arrowIdx = arrow.indexOf(" --> ");
				if (arrowIdx >= 0) {
						return arrow.substring(arrowIdx + 5).trim();
				}
				// Pattern: "B <|-- A" → target is B
				int extIdx = arrow.indexOf(" <|-- ");
				if (extIdx >= 0) {
						return arrow.substring(0, extIdx).trim();
				}
				// Pattern: "B <|.. A" → target is B
				int impIdx = arrow.indexOf(" <|.. ");
				if (impIdx >= 0) {
						return arrow.substring(0, impIdx).trim();
				}
				return null;
		}

		/** Generates a PlantUML package dependency diagram. */
		public String generatePackageDiagram(JavaSourceScanner.ScanResult result) {
				StringBuilder sb = new StringBuilder();
				sb.append("@startuml\n");
				sb.append("' Generated by cland-plantuml - Package Diagram\n\n");

				// Collect packages from filtered types
				Set<String> packages =
								result.types.values().stream()
												.map(t -> t.packageName)
												.filter(Objects::nonNull)
												.collect(Collectors.toCollection(TreeSet::new));

				for (String pkg : packages) {
						sb.append("package ").append(pkg).append(" {\n}\n\n");
				}

				// Package dependencies
				for (Map.Entry<String, Set<String>> entry : result.packageDeps.entrySet()) {
						String from = entry.getKey();
						for (String to : entry.getValue()) {
								// Only show dependency if the target package is in our filtered set
								if (packages.stream().anyMatch(to::startsWith)) {
										sb.append(from).append(" --> ").append(to).append("\n");
								}
						}
				}

				sb.append("@enduml\n");
				return sb.toString();
		}

		/** Generates a PlantUML sequence diagram from extracted method calls. */
		public String generateSequenceDiagram(JavaSourceScanner.ScanResult result) {
				return generateSequenceDiagram(result, List.of());
		}

		public String generateSequenceDiagram(
						JavaSourceScanner.ScanResult result, List<String> focusPackages) {
				StringBuilder sb = new StringBuilder();
				sb.append("@startuml\n");
				sb.append("' Generated by cland-plantuml - Sequence Diagram\n");
				if (!focusPackages.isEmpty()) {
						sb.append("' Focus packages: ").append(String.join(", ", focusPackages)).append("\n");
				}
				sb.append("' Note: calls to unresolved types (variables, external libs) are omitted\n\n");
				sb.append("autonumber \"<b>#. \"\n");
				sb.append("' Arrows show call direction only (static analysis — no return flow)\n\n");

				// Build simple-name → qualified-name map from known types
				Map<String, String> simpleNameMap = new HashMap<>();
				for (String qn : result.types.keySet()) {
						String simple = qn.contains(".") ? qn.substring(qn.lastIndexOf('.') + 1) : qn;
						simpleNameMap.put(simple, qn);
				}

				// Resolve a target type string to a qualified name if possible
				java.util.function.Function<String, String> resolveTarget =
								target -> {
										if (result.types.containsKey(target)) return target;
										String qualified = simpleNameMap.get(target);
										if (qualified != null) return qualified;
										return null;
								};

				// Collect valid calls, grouped by (callerType, callerMethod), sorted by line
				// Map: "callerType.callerMethod" → list of calls
				Map<String, List<TypeModel.MethodCall>> callsByMethod = new LinkedHashMap<>();
				Set<String> allParticipants = new LinkedHashSet<>();
				Set<String> calledKeys = new HashSet<>(); // methods that are called by someone

				for (TypeModel type : result.types.values()) {
						for (TypeModel.MethodCall call : type.methodCalls) {
								String from = call.callerType;
								String to;
								if ("this".equals(call.targetType)) {
										to = from; // self-call: use caller's own type
								} else {
										to = resolveTarget.apply(call.targetType);
								}
								if (to == null) continue;
								if (!result.types.containsKey(from)) continue;

								// Focus filter: if focusPackages specified, both caller and target must match
								if (!focusPackages.isEmpty()
												&& !isInFocus(from, focusPackages)
												&& !isInFocus(to, focusPackages)) continue;

								String key = from + "." + call.callerMethod;
								callsByMethod.computeIfAbsent(key, k -> new ArrayList<>()).add(call);
								allParticipants.add(from);
								allParticipants.add(to);

								// Record that this target method is called (including self-calls via "this")
								String targetMethodKey =
												"this".equals(call.targetType)
																? call.callerType + "." + call.targetMethod
																: to + "." + call.targetMethod;
								calledKeys.add(targetMethodKey);
						}
				}

				// Sort calls within each method by line number
				for (List<TypeModel.MethodCall> list : callsByMethod.values()) {
						list.sort(Comparator.comparingInt(c -> c.lineNumber));
				}

				if (allParticipants.isEmpty()) {
						sb.append("' No method calls detected between known types\n");
						sb.append("@enduml\n");
						return sb.toString();
				}

				// Emit participant declarations
				for (String p : allParticipants) {
						String label = p.contains(".") ? p.substring(p.lastIndexOf('.') + 1) : p;
						sb.append("participant \"").append(label).append("\" as ").append(p).append("\n");
				}
				sb.append("\n");

				// Identify root methods: have calls but are never called by any known type
				// Sort roots: main() first, then by name
				List<String> roots =
								callsByMethod.keySet().stream()
												.filter(k -> !calledKeys.contains(k))
												.sorted(
																(a, b) -> {
																		boolean aMain = a.endsWith(".main");
																		boolean bMain = b.endsWith(".main");
																		if (aMain && !bMain) return -1;
																		if (!aMain && bMain) return 1;
																		return a.compareTo(b);
																})
												.collect(Collectors.toList());

				// Track which methods we've already emitted (avoid cycles)
				Set<String> emitted = new HashSet<>();

				// Emit call tree from each root
				for (String rootKey : roots) {
						emitCallTree(sb, rootKey, callsByMethod, resolveTarget, emitted, 0);
				}

				sb.append("@enduml\n");
				return sb.toString();
		}

		/** Check if a qualified type name matches any focus package prefix. */
		private static boolean isInFocus(String qualifiedName, List<String> focusPackages) {
				for (String pkg : focusPackages) {
						if (qualifiedName.equals(pkg)
										|| qualifiedName.startsWith(pkg + ".")
										|| qualifiedName.startsWith(pkg + "/")) {
								return true;
						}
				}
				return false;
		}

		/**
		 * Truncate long argument strings for display in sequence diagram labels. Strips surrounding
		 * brackets from NodeList.toString(), truncates to 80 chars.
		 */
		private static String truncateArgs(String args) {
				if (args == null || args.isEmpty() || "[]".equals(args)) return "";
				// Strip surrounding brackets from NodeList.toString()
				String cleaned = args;
				if (cleaned.startsWith("[") && cleaned.endsWith("]")) {
						cleaned = cleaned.substring(1, cleaned.length() - 1);
				}
				// Truncate long strings
				if (cleaned.length() > 80) {
						cleaned = cleaned.substring(0, 77) + "...";
				}
				return cleaned;
		}

		/**
		 * Recursively emit a method's call tree using PlantUML {@code group} blocks. Calls already
		 * emitted are skipped (cycle guard).
		 */
		private void emitCallTree(
						StringBuilder sb,
						String methodKey,
						Map<String, List<TypeModel.MethodCall>> callsByMethod,
						java.util.function.Function<String, String> resolveTarget,
						Set<String> emitted,
						int depth) {

				List<TypeModel.MethodCall> calls = callsByMethod.get(methodKey);
				if (calls == null || calls.isEmpty()) return;

				// Extract short label for this method
				String label =
								methodKey.contains(".")
												? methodKey.substring(methodKey.lastIndexOf('.') + 1)
												: methodKey;
				String typeLabel =
								methodKey.contains(".") ? methodKey.substring(0, methodKey.lastIndexOf('.')) : "";
				typeLabel =
								typeLabel.contains(".")
												? typeLabel.substring(typeLabel.lastIndexOf('.') + 1)
												: typeLabel;

				// Start group block for nested calls
				if (depth > 0) {
						sb.append("group ").append(typeLabel).append(".").append(label).append("()\n");
				} else {
						// Root level: use == separator only when there are multiple roots
						sb.append("== ").append(typeLabel).append(".").append(label).append("() ==\n");
				}

				emitted.add(methodKey);

				for (TypeModel.MethodCall call : calls) {
						String from = call.callerType;
						String to;
						boolean isSelfCall = "this".equals(call.targetType);
						if (isSelfCall) {
								to = from; // self-call: same type
						} else {
								to = resolveTarget.apply(call.targetType);
						}
						if (to == null) continue;

						// Emit the call arrow
						sb.append(from)
										.append(" -> ")
										.append(to)
										.append(": ")
										.append(call.targetMethod)
										.append("(")
										.append(truncateArgs(call.arguments))
										.append(")\\n")
										.append("(line ")
										.append(call.lineNumber)
										.append(")")
										.append("\n");

						// Recursively emit callee's own calls
						String calleeKey = (isSelfCall ? from : to) + "." + call.targetMethod;
						if (!emitted.contains(calleeKey) && callsByMethod.containsKey(calleeKey)) {
								emitCallTree(sb, calleeKey, callsByMethod, resolveTarget, emitted, depth + 1);
						}
				}

				// Close group block
				if (depth > 0) {
						sb.append("end\n");
				}
		}
}
