/*
 * This source file was generated by the Skeletal project creation tool.
 * https://github.com/cbmarcum/skeletal
 */
package org.cland.plantuml

import spock.lang.Specification

class ClandPlantumlSpec extends Specification {
    def "application has a greeting"() {
        given: "a new application"
        def app = new ClandPlantuml()

        when: "getting a greeting"
        def result = app.greeting

        then: "there is a greeting"
        result != null
    }

    def "application has the correct greeting"() {
        given: "a new application"
        def app = new ClandPlantuml()

        when: "getting a greeting"
        def result = app.greeting

        then: "the greeting is correct"
        result == "Hello World!"
    }
}
